name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Stop all the containers
      run: sudo docker stop $(sudo docker ps -a -q)
    - name: Remove all the containers
      run: sudo docker rm $(sudo docker ps -a -q) || true
    - name: Remove all the images
      run: sudo docker rmi $(sudo docker images -q) || true
    - name: Pull the docker image from Dockerhub
      run: sudo docker pull vtaneja/cicd_pipeline:latest
    - name: Run the new container
      run: sudo docker run -d --name cicd_pipeline-container -p 8000:8000 vtaneja/cicd_pipeline:latest
